[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
description = "Tokio based asynchronous MySql client library."
documentation = "https://docs.rs/mysql_async"
keywords = ["mysql", "database", "asynchronous", "async"]
license = "MIT/Apache-2.0"
name = "mysql_async"
readme = "README.md"
repository = "https://github.com/blackbeam/mysql_async"
version = "0.21.0"
exclude = ["test/*"]
edition = "2018"

[dependencies]
bytes = "0.5.2"
crossbeam = "0.7"
futures-core = "0.3"
futures-util = "0.3"
futures-sink = "0.3"
mio-named-pipes = "0.1.6"
mysql_common = { git = "https://github.com/tonygrue/rust_mysql_common.git" }
native-tls = "0.2"
percent-encoding = "2.1.0"
pin-project = "0.4.6"
serde = "1"
serde_json = "1"
thiserror = "1.0.4"
tokio = { version = "0.2.0-alpha.6", features = ["io-util", "net", "sync", "fs", "rt-core", "time", "stream", "macros"] }
tokio-util = { version = "0.2.0-alpha.6", features = ["codec"] }
tokio-tls = "0.3.0-alpha.6"
twox-hash = "1"
url = "2.1"

[dev-dependencies]
lazy_static = "1"
tempfile = "3.1.0"

[features]
nightly = []

[lib]
name = "mysql_async"
path = "src/lib.rs"

[profile.bench]
debug = true
